#!/usr/bin/env bash

export USER_ID=$(id -u)
export GROUP_ID=$(id -g)

export LD_PRELOAD=libnss_wrapper.so
export NSS_WRAPPER_PASSWD=/usr/local/share/passwd
export NSS_WRAPPER_GROUP=/etc/group

if [ ! -f /usr/local/share/passwd ]; then
    echo "File not found!"
fi

envsubst < /usr/local/share/passwd.template > /tmp/passwd

sh -c "$@"
